//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSchema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCarReminder
    {
        public int Id { get; set; }
        public int MyCarId { get; set; }
        public string DtEntered { get; set; }
        public string Message { get; set; }
        public string Title { get; set; }
        public string DtRemind { get; set; }
        public string Status { get; set; }
        public int MyReminderTypeId { get; set; }
        public string SendNotification { get; set; }
    
        public virtual MyCar MyCar { get; set; }
        public virtual MyReminderType MyReminderType { get; set; }
    }
}
