//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSchema.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyCarDBContainer : DbContext
    {
        public MyCarDBContainer()
            : base("name=MyCarDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MyCar> MyCars { get; set; }
        public virtual DbSet<MyCarModel> MyCarModels { get; set; }
        public virtual DbSet<MyCarMake> MyCarMakes { get; set; }
        public virtual DbSet<MyCarType> MyCarTypes { get; set; }
        public virtual DbSet<MyCarFuel> MyCarFuels { get; set; }
        public virtual DbSet<MyCarTransmission> MyCarTransmissions { get; set; }
        public virtual DbSet<MyCarDrivetrain> MyCarDrivetrains { get; set; }
        public virtual DbSet<MyGarage> MyGarages { get; set; }
        public virtual DbSet<MyDriver> MyDrivers { get; set; }
        public virtual DbSet<MyCarTrx> MyCarTrxes { get; set; }
        public virtual DbSet<MyCarTrxGarage> MyCarTrxGarages { get; set; }
        public virtual DbSet<MyCarTrxDriver> MyCarTrxDrivers { get; set; }
        public virtual DbSet<MyCarTrxFuel> MyCarTrxFuels { get; set; }
        public virtual DbSet<MyCarTrxService> MyCarTrxServices { get; set; }
        public virtual DbSet<MyCarServiceType> MyCarServiceTypes { get; set; }
        public virtual DbSet<MyCarTrxExpense> MyCarTrxExpenses { get; set; }
        public virtual DbSet<MyCarExpenseType> MyCarExpenseTypes { get; set; }
        public virtual DbSet<MyCarReminder> MyCarReminders { get; set; }
        public virtual DbSet<MyReminderType> MyReminderTypes { get; set; }
        public virtual DbSet<MyAccount> MyAccounts { get; set; }
        public virtual DbSet<MySupportLogin> MySupportLogins { get; set; }
        public virtual DbSet<MyGarageLogin> MyGarageLogins { get; set; }
        public virtual DbSet<MyDriverLogin> MyDriverLogins { get; set; }
    }
}
