//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSchema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCarTrx
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MyCarTrx()
        {
            this.MyCarGarageTrxes = new HashSet<MyCarTrxGarage>();
            this.MyCarTrxDrivers = new HashSet<MyCarTrxDriver>();
            this.MyCarTrxFuels = new HashSet<MyCarTrxFuel>();
            this.MyCarServices = new HashSet<MyCarTrxService>();
            this.MyCarTrxExpenses = new HashSet<MyCarTrxExpense>();
        }
    
        public int Id { get; set; }
        public int MyCarTrxTypeId { get; set; }
        public int MyCarId { get; set; }
        public string TrxDate { get; set; }
        public string TrxTime { get; set; }
        public string TrxMileage { get; set; }
        public string EnteredBy { get; set; }
    
        public virtual MyCar MyCar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyCarTrxGarage> MyCarGarageTrxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyCarTrxDriver> MyCarTrxDrivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyCarTrxFuel> MyCarTrxFuels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyCarTrxService> MyCarServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyCarTrxExpense> MyCarTrxExpenses { get; set; }
    }
}
