//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSchema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyGarageLogin
    {
        public int Id { get; set; }
        public int MyGarageId { get; set; }
        public int MySupportLoginId { get; set; }
    
        public virtual MyGarage MyGarage { get; set; }
        public virtual MySupportLogin MySupportLogin { get; set; }
    }
}
