//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCarTrxFuel
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public int MyCarTrxId { get; set; }
    
        public virtual MyCarTrx MyCarTrx { get; set; }
    }
}
