//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyDriver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MyDriver()
        {
            this.MyCarTrxDrivers = new HashSet<MyCarTrxDriver>();
            this.MyDriverLogins = new HashSet<MyDriverLogin>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LicNo { get; set; }
        public string Remarks { get; set; }
        public int MyAccountId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyCarTrxDriver> MyCarTrxDrivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyDriverLogin> MyDriverLogins { get; set; }
        public virtual MyAccount MyAccount { get; set; }
    }
}
