//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MyCar()
        {
            this.MyCarTrxes = new HashSet<MyCarTrx>();
            this.MyCarReminders = new HashSet<MyCarReminder>();
        }
    
        public int Id { get; set; }
        public string Year { get; set; }
        public string Variant { get; set; }
        public int MyCarModelId { get; set; }
        public int MyCarFuelId { get; set; }
        public int MyCarTransmissionId { get; set; }
        public int MyCarDrivetrainId { get; set; }
        public string PlateNo { get; set; }
        public string Conduction { get; set; }
        public string Vin { get; set; }
        public int MyAccountId { get; set; }
    
        public virtual MyCarModel MyCarModel { get; set; }
        public virtual MyCarFuel MyCarFuel { get; set; }
        public virtual MyCarTransmission MyCarTransmission { get; set; }
        public virtual MyCarDrivetrain MyCarDrivetrain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyCarTrx> MyCarTrxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyCarReminder> MyCarReminders { get; set; }
        public virtual MyAccount MyAccount { get; set; }
    }
}
